name: ooooo

on: 
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'log'
        required: false
        default: 'info'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: dependencies
      run: npm install
    - name: build
      run: npm run build
    - name: test google tcp
      run: |
        timeout 5 bash -c "echo 'HEAD / HTTP/1.0\r\n\r\n' > /dev/tcp/www.google.com/443"
        echo "Raw TCP exit code: $?"
    - name: checking workflow HZ
      run: |
        grep '^CONFIG_HZ=' /boot/config-$(uname -r)
    - name: run the shit
      env:
        FILE: ${{ secrets.FILE }}
      run: |
        while true; do
          echo "logi logi logi"
          sleep 300
        done &
        mkdir src
        echo $FILE > src/receiver.ts
        npm run dev 2>&1
