name: ooooo

on: 
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'log'
        required: false
        default: 'info'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: dependencies
      run: npm install
    - name: build
      env:
        FILE: ${{ secrets.FILE }}
      run: |
        mkdir src
        echo "$FILE" | base64 --decode > src/receiver.ts
        npm run build
    - name: run the shit
      run: |
        while true; do
          echo "logi logi logi"
          sleep 300
        done &
        npm run dev 2>&1
